/*
 * This file is generated by jOOQ.
 */
package com.kpdoggie.ingest.fileingest.schema;


import com.kpdoggie.ingest.fileingest.schema.tables.People;
import com.kpdoggie.ingest.fileingest.schema.tables.records.PeopleRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PeopleRecord, Integer> IDENTITY_PEOPLE = Identities0.IDENTITY_PEOPLE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PeopleRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PeopleRecord, Integer> IDENTITY_PEOPLE = Internal.createIdentity(People.PEOPLE, People.PEOPLE.PERSON_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PeopleRecord> CONSTRAINT_8 = Internal.createUniqueKey(People.PEOPLE, "CONSTRAINT_8", new TableField[] { People.PEOPLE.PERSON_ID }, true);
    }
}
