/*
 * This file is generated by jOOQ.
 */
package com.kpdoggie.ingest.fileingest.schema;


import com.kpdoggie.ingest.fileingest.schema.tables.CachedMapping;
import com.kpdoggie.ingest.fileingest.schema.tables.CachedS;
import com.kpdoggie.ingest.fileingest.schema.tables.CachedSs;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CACHED_MAPPING</code>.
     */
    public static final CachedMapping CACHED_MAPPING = CachedMapping.CACHED_MAPPING;

    /**
     * The table <code>PUBLIC.CACHED_S</code>.
     */
    public static final CachedS CACHED_S = CachedS.CACHED_S;

    /**
     * The table <code>PUBLIC.CACHED_SS</code>.
     */
    public static final CachedSs CACHED_SS = CachedSs.CACHED_SS;
}
