DROP TABLE CACHED_S IF EXISTS;
CREATE TABLE CACHED_S (
S_ID INT IDENTITY PRIMARY KEY,
S_NAME VARCHAR(20)
);

DROP TABLE CACHED_SS IF EXISTS;
CREATE TABLE CACHED_SS (
SS_ID INT IDENTITY PRIMARY KEY,
SS_NAME VARCHAR(20),
S_ID INT
);

DROP TABLE CACHED_MAPPING IF EXISTS;
CREATE TABLE CACHED_MAPPING (
S_ID INT,
SS_ID INT,
MAPPED_S_ID INT
);
